### ISSUE TITLE
Use the `arguments` table

### ISSUE THREAD

**Issue by FunctionalMetatable** [CodeGuy92/anti-profanity#2]
https://github.com/CodeGuy92/anti-profanity/blob/4c08daa69e5ec865221de19aa579301139f35eec/script.js#L48

**Comment by CodeGuy92** [comment]
what the fuck is the `arguments` table

**Comment by FunctionalMetatable** [comment]
stop swearing :/

**Comment by CodeGuy92** [comment]
> stop swearing :/

Ok, just explain to me.

**Comment by CodeGuy92** [comment]
What is the `arguments` table and what does it do

**Comment by FunctionalMetatable** [comment]
the arguments table is a table of **all** the arguments passed into the function, e.g:
```js
function filter(replace) {
  let args = arguments;
  // find the first argument
  console.log(args[0]) // the replace arg.
  console.log(args[1]) // the second argument, its not defined but we can use it thru the arguments table.
}

filter("this is what gets replaced", "the second arg")
```

**Comment by CodeGuy92** [comment]
> the arguments table is a table of **all** the arguments passed into the function, e.g:
> 
> ```js
> function filter(replace) {
>   let args = arguments;
>   // find the first argument
>   console.log(args[0]) // the replace arg.
>   console.log(args[1]) // the second argument, its not defined but we can use it thru the arguments table.
> }
> 
> filter("this is what gets replaced", "the second arg")
> ```

Oh, i get it. So i can use a "for" loop for each argument? Let me search w3schools

**Comment by CodeGuy92** [comment]
i don't understand how to do this

**Comment by CodeGuy92** [comment]
i'll do further research tomorrow

**Comment by CodeGuy92** [comment]
it's 2 AM here

**Comment by CodeGuy92** [comment]
bye

**Comment by CodeGuy92** [comment]
fixed https://github.com/CodeGuy92/anti-profanity/commit/4778d2f6a0945bceee359dd42dbd7a15fad9ae00
