### ISSUE TITLE
Filter letter for letter

### ISSUE THREAD

**Issue by Shluffy** [CodeGuy92/anti-profanity#3]
it seems to be:
```
str = What is a booty?;
filterWords(str, "*");
```
returns: `What is a *?` (or the readme seems to indicate this)

i think it should be:
```
str = What is a booty?;
filterWords(str, "*");
```
would return: `What is a *****?`

by matching the length of censor, or make a new filter function so it could still be filtered as `filterWords(<string>, [Removed By Filter])`
edit: making a new function is probably better as `filterWords("What is a booty?", [Removed By Filter])` would return `What is a [Removed By Filter][Removed By Filter][Removed By Filter][Removed By Filter][Removed By Filter]?`

**Comment by CodeGuy92** [comment]
Yeah sure, i'll get workin'.

**Comment by CodeGuy92** [comment]
Actually i'd have to create a script to replace each letter of a substring (using replace function) and i have absolutely no idea how to do this. A PR would be cool, i'll just improvise for now.

**Comment by Shluffy** [comment]
Okay, I think that the function would be like `filterWordsByLetter("Why is booty filtered?", "*")` and then the function would replace `booty` with the length of the word hardcoded in, and would be like `("booty/gi", censor + censor + censor + censor + censor)` and would return `Why is ***** filtered?`. I guess I will work on the actual coding part now.
however, if the censor is `1` will it return `Why is 5 filtered?`

**Comment by CodeGuy92** [comment]
> however, if the censor is `1` will it return `Why is 5 filtered?`

I don't get what you mean...

> Okay, I think that the function would be like `filterWordsByLetter("Why is booty filtered?", "*")` and then the function would replace `booty` with the length of the word hardcoded in, and would be like `("booty/gi", censor + censor + censor + censor + censor)` and would return `Why is ***** filtered?`. I guess I will work on the actual coding part now.

Actually we can just detect the length of the censor. If it's 1, then do that. If it's over 2 characters, use the current system.

**Comment by Shluffy** [comment]
> > however, if the censor is `1` will it return `Why is 5 filtered?`
> 
> I don't think so
>
i will test that if i will make this 
> > Okay, I think that the function would be like `filterWordsByLetter("Why is booty filtered?", "*")` and then the function would replace `booty` with the length of the word hardcoded in, and would be like `("booty/gi", censor + censor + censor + censor + censor)` and would return `Why is ***** filtered?`. I guess I will work on the actual coding part now.
> 
> Actually we can just detect the length of the censor. If it's 1, then do that. If it's over 2 characters, use the current system.

Not sure what you mean here

**Comment by CodeGuy92** [comment]
> > > however, if the censor is `1` will it return `Why is 5 filtered?`
> > 
> > 
> > I don't think so
> 
> i will test that if i will make this
> 
> > > Okay, I think that the function would be like `filterWordsByLetter("Why is booty filtered?", "*")` and then the function would replace `booty` with the length of the word hardcoded in, and would be like `("booty/gi", censor + censor + censor + censor + censor)` and would return `Why is ***** filtered?`. I guess I will work on the actual coding part now.
> > 
> > 
> > Actually we can just detect the length of the censor. If it's 1, then do that. If it's over 2 characters, use the current system.
> 
> Not sure what you mean here

```
filterWords("fuck me", "*") // Does your idea and duplicates itself for the number of letters

filterWords("fuck me", "***") // Will use the current system and will not duplicate itself
```

**Comment by gosoccerboy5** [comment]
Tip - when using .replaceAll, you can actually use a function
```js
String.prototype.times = function (amt) {
    let temp = "";
    for (let i = 0; i < amt; i++) temp += this;
    return temp;
};
// "loser" is a bad word here
alert(prompt().replaceAll(/loser/gi, n => "*".times(n.length)));
```
enter "loser" and it replaces it with the right number of *'s

**Comment by gosoccerboy5** [comment]
> filterWords(":)", "*") // Does your idea and duplicates itself for the number of letters
> 
> filterWords(":)", "***") // Will use the current system and will not duplicate itself

please clean this if possible..

**Comment by CodeGuy92** [comment]
> Tip - when using .replaceAll, you can actually use a function
> 
> ```js
> String.prototype.times = function (amt) {
>     let temp = "";
>     for (let i = 0; i < amt; i++) temp += this;
>     return temp;
> };
> // "loser" is a bad word here
> alert(prompt().replaceAll(/loser/gi, n => "*".times(n.length)));
> ```
> 
> enter "loser" and it replaces it with the right number of *'s

make a pull request

**Comment by CodeGuy92** [comment]
Actually we can use `"test".repeat(17);`
this will return `testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest`

**Comment by gosoccerboy5** [comment]
I literally didn't know Strings had a .repeat method. I will now promptly update all my code that has this
