### ISSUE TITLE
aaaaaaa

### ISSUE THREAD

**Issue by gosoccerboy5** [CodeGuy92/anti-profanity#7]
my eyes
please just return `strfiltered.includes("Q29kZVdvcmQxMjM=")` instead of using a CONDITIONAL RETURN STATEMENT :(

https://github.com/CodeGuy92/anti-profanity/blob/c060f57d598d02ae76d1973706ebf5fd63a9f066/script.js#L186-L190

**Comment by CodeGuy92** [comment]
ok

**Comment by CodeGuy92** [comment]
please stick to the issue templates also
