### ISSUE TITLE
Upgrading the current code.

### ISSUE THREAD

**Issue by CodeGuy92** [CodeGuy92/anti-profanity#8]
Currently we're upgrading the current code to a more efficient method of filtering.
```
var myStringArray = ["Hello", "World"];
var arrayLength = myStringArray.length;
for (var i = 0; i < arrayLength; i++) {
    var filtered = raw.replaceAll(myStringArray[i]);
}
```

Post any related ideas here.

**Comment by CodeGuy92** [comment]
https://github.com/CodeGuy92/anti-profanity/commit/499abf179953c6a6edfd7d1ae509cc327973e441

**Comment by CodeGuy92** [comment]
Ok fully upgraded

**Comment by gosoccerboy5** [comment]
I hate to post on a closed topic, but could you declare the variable _before_ the loop so you're not redeclaring it every iteration through the list?
